name:                neco
version:             0.1.0.0
github:              himura/neco
license:             BSD3
author:              Takahiro Himura
maintainer:          taka@himura.jp
copyright:           2017 Takahiro Himura

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Network Client
category:            Network

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/himura/neco#readme>
tested-with:         GHC == 7.8.4, GHC == 7.10.3, GHC == 8.0.2, GHC == 8.2.1

dependencies:
- base >= 4.7 && < 5
- aeson
- attoparsec
- authenticate-oauth
- bytestring >= 0.10.2
- http-client >= 0.4.0
- http-client-tls
- http-types
- profunctors
- text

when:
  - condition: impl(ghc < 8.0)
    dependencies:
      - transformers

flags:
  build-sample:
    default: False
    manual: True

ghc-options: -Wall

library:
  source-dirs: src

executables:
  sample:
    main:                sample.hs
    source-dirs:         sample
    when:
      - condition: flag(build-sample)
        then:
          ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
          dependencies:
           - neco
           - lens
           - twitter-types-lens
        else:
          buildable: False

tests:
  neco-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - neco
    - base64-bytestring
    - lens
    - lens-aeson
    - tasty >= 0.7
    - tasty-hunit
    - tasty-quickcheck
    - tasty-th
    - text
