name:                rio
version:             0.1.0.0
github:              himura/rio
license:             BSD3
author:              Takahiro Himura
maintainer:          taka@himura.jp
copyright:           2017 Takahiro Himura

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Remote IO
category:            Network

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/himura/rio#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- attoparsec
- bytestring >= 0.10.2
- http-client >= 0.4.0
- http-client-tls
- http-types

library:
  source-dirs: src

tests:
  rio-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rio
